logging:
  level:
    ru.lapotko.coingoal: debug

server:
  port: 9091
cors:
  origin:
    front: "http://localhost:4200"
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5555/coingoal
    username: postgres
    password: postgres
