version: '3.7'
services:
  coingoal-postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coingoal
    expose:
      - 5555
    ports:
      - 5555:5555
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  ng-coingoal:
    container_name: ng-coingoal
    build: ../presentation/ng-coingoal
    restart: on-failure
    ports:
      - 4200:80
    environment:
      NG_ENVIRONMENT: docker
  rest-coingoal:
    container_name: rest-coingoal
    build: ../application/rest
    restart: on-failure
    ports:
      - 9090:9090
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - coingoal-postgres
